AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  Severity: refactor
  Max: 120

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FrozenStringLiteralComment:
  Severity: refactor
