language: ruby
cache: bundler
sudo: false
dist: xenial

script:
  - bundle install
  - bundle exec rubocop --version
  - bundle exec rubocop
  - bundle exec foodcritic --version
  - bundle exec foodcritic . --exclude spec
  - bundle exec rspec -f doc spec
before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_5ef3ee01d0c9_key -iv $encrypted_5ef3ee01d0c9_iv -in .travis/supermarket.pem.enc -out .travis/supermarket.pem -d; fi
deploy:
  provider: script
  script: rvm use 2.4 do bash -c 'bundle install && bundle exec knife supermarket share remote_file_s3 -o .. --config-option node_name=mkulka --config-option client_key=.travis/supermarket.pem -m https://supermarket.chef.io'
  skip_cleanup: true
  on:
    tags: true
